import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
const html=fs.readFileSync(new URL('../extension/popup.html',import.meta.url),'utf8');
async function popup(source){const d=new JSDOM(html,{url:'https://extension.test'});globalThis.document=d.window.document;const calls=[];globalThis.chrome={tabs:{query:async()=>[{id:7,url:source,windowId:1}],captureVisibleTab:async()=>{calls.push('screenshot');return 'data:image/png;base64,AA==';}},scripting:{executeScript:async()=>{calls.push('dom');return [{result:{fields:{title:'Fixture',primary_text:'Public evidence'},media_references:[],observed_url:source}}];}},runtime:{sendNativeMessage:async(host,msg)=>{calls.push(msg);return msg.command==='health'?{ok:true,allowed_capture_origins:['https://example.com']}:{ok:true,status:'partial',id:'a'.repeat(32),note:'/fixture/note.md'};}},storage:{local:{get:async()=>({}),set:async()=>{}}}};await import(`../extension/popup.js?test=${Math.random()}`);return {d,calls,$:id=>d.window.document.getElementById(id),tick:()=>new Promise(r=>setTimeout(r,20))};}
test('Popup manual save and surfaced receipt use native host',async()=>{let p=await popup('https://example.com/article');p.$('public').checked=true;p.$('title').value='Manual';p.$('save').click();await p.tick();assert.equal(p.calls.filter(x=>x.command==='workflow'&&x.mode==='save_obsidian').length,1);assert.match(p.$('status').textContent,/PARTIAL/);assert.ok(!p.calls.includes('dom'));});
test('Popup preview is explicit and editable',async()=>{let p=await popup('https://example.com/article');assert.ok(!p.calls.includes('dom'));p.$('public').checked=true;p.$('preview').click();await p.tick();assert.ok(p.calls.includes('dom'));assert.equal(p.$('title').value,'Fixture');});
test('Instagram active page never autofills or captures',async()=>{let p=await popup('https://www.instagram.com/p/test/');assert.equal(p.$('source').value,'');p.$('public').checked=true;p.$('screenshot').checked=true;p.$('save').click();await p.tick();assert.ok(!p.calls.some(x=>x.command==='capture'||x.command==='workflow'));assert.ok(!p.calls.includes('dom'));assert.ok(!p.calls.includes('screenshot'));});
test('External pasted Instagram reference does not read page or download',async()=>{let p=await popup('https://example.com/');p.$('source').value='https://www.instagram.com/p/test/';p.$('source').dispatchEvent(new p.d.window.Event('change'));p.$('public').checked=true;p.$('notes').value='External intent';p.$('save').click();await p.tick();let msg=p.calls.find(x=>x.command==='capture');assert.deepEqual(msg.payload.fields,{notes:'External intent'});assert.equal(msg.payload.method,'instagram-url-handoff');assert.ok(!p.calls.includes('dom'));assert.ok(!p.calls.includes('screenshot'));p.$('download').click();await p.tick();assert.ok(!p.calls.some(x=>x.mode==='quick_download'));});
test('Quick Download uses separate native workflow',async()=>{let p=await popup('https://example.com/article');p.$('public').checked=true;p.$('rights').value='licensed';p.$('asset').value='https://example.com/clip.mp4';p.$('download').click();await p.tick();let msg=p.calls.find(x=>x.mode==='quick_download');assert.equal(msg.command,'workflow');assert.ok(!p.calls.some(x=>x.mode==='save_obsidian'));assert.ok(!p.calls.includes('dom'));});
test('Missing companion surfaces failure',async()=>{let p=await popup('https://example.com');p.$('public').checked=true;chrome.runtime.sendNativeMessage=async()=>{throw Error('Native host not found');};p.$('save').click();await p.tick();assert.match(p.$('status').textContent,/Native host not found/);assert.equal(p.$('status').dataset.error,'true');});
